name: Cypress Tests

on: [push]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
     - name: Run Commands with a Secret
        run: |
            echo ${{secrets.API_KEY}} > cypress.env.json
      - name: Checkout
        uses: actions/checkout@v3
      
      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests
      - name: Cypress run
        uses: cypress-io/github-action@v5 # use the explicit version number
     
